global:
  scrape_interval:     1s

scrape_configs:
  - job_name: 'notary-process'

    scrape_interval: 1s
    metrics_path: /process-metrics

    static_configs:
      - targets: ['tlsn.eternis.ai:7047']
  - job_name: 'notary-application'

    scrape_interval: 1s
    metrics_path: /app-metrics

    static_configs:
      - targets: ['tlsn.eternis.ai:7047']
